@startuml

start

:Получить список доступных инструментов;

:Альфа-модель делает прогноз по каждому из доступных инструментов;

:Риск-модель расчитывает объем сделки, разрешает покупку или продажу актива
(Допустим, после сделки будет нарушенна диверсиффикация)
(Наверное, нужно учесть момент, что нельзя прям жёстко ограничивать пропорции портфеля.
Допустим, если сигнал на продажу при имеющихся обретённых активов, 
то их нужно продать, даже если поменяются пропорции);

:Модель транзакционных издержек - Покрывает ли прогноз коммисию?;

:Модель-исполнения получает инструмент, количество и отправляет запрос на исполнения позиции;

stop

@enduml