@startuml

component "Альфа модель" as Alpha
component "Модель рисков" as Risk   
component "Транзакционные издержки" as TransactionCost
component Портфель as Portfolio
component "Модуль Исполнения" as Execution

Alpha --> Portfolio
Risk --> Portfolio
TransactionCost --> Portfolio
Portfolio --> Execution
Execution --> Portfolio

@enduml